import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_displaymode/flutter_displaymode.dart';
import 'package:google_fonts/google_fonts.dart';

import 'app.dart';
// Generated by `flutterfire configure`. If you haven't run that yet, the
// import below will be red — comment it out + use Firebase.initializeApp()
// without options, but auth + Firestore will fail until you do.
import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Draw edge-to-edge with a transparent status/nav bar from the very first
  // frame — otherwise the AppBar-less Home tab shows a black status bar until
  // a tab switch forces a relayout (Android 15 edge-to-edge behaviour).
  SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);
  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    statusBarColor: Colors.transparent,
    systemNavigationBarColor: Colors.transparent,
  ));
  // Opt into the display's highest refresh rate (120Hz where available).
  // No-op / throws on platforms without the API — safe to ignore.
  try {
    await FlutterDisplayMode.setHighRefreshRate();
  } catch (_) {}
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    debugPrint('[main] Firebase init skipped: $e');
  }
  // Warm the Inter weights the theme uses so the first real frame doesn't show
  // a font swap from the platform fallback. Fire-and-forget — we deliberately
  // DON'T await, so this never delays the first frame (awaiting it here was
  // making cold start sit on a black screen before the splash appeared).
  try {
    GoogleFonts.inter();
    GoogleFonts.inter(fontWeight: FontWeight.w700);
    GoogleFonts.inter(fontWeight: FontWeight.w800);
  } catch (_) {}
  runApp(const ProviderScope(child: AerisExpenseApp()));
}
