import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:flutter_displaymode/flutter_displaymode.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'app.dart';
import 'models/currency.dart';
import 'providers/theme_provider.dart';
import 'utils/formatters.dart';
// Generated by `flutterfire configure`. If you haven't run that yet, the
// import below will be red — comment it out + use Firebase.initializeApp()
// without options, but auth + Firestore will fail until you do.
import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Draw edge-to-edge with a transparent status/nav bar from the very first
  // frame — otherwise the AppBar-less Home tab shows a black status bar until
  // a tab switch forces a relayout (Android 15 edge-to-edge behaviour).
  SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);
  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    statusBarColor: Colors.transparent,
    systemNavigationBarColor: Colors.transparent,
    // Match the native launch window exactly (light icons on the dark
    // canvas, no grey contrast scrim) so start-up has no visible change.
    statusBarIconBrightness: Brightness.light,
    systemNavigationBarIconBrightness: Brightness.light,
    systemStatusBarContrastEnforced: false,
    systemNavigationBarContrastEnforced: false,
  ));
  // Opt into the display's highest refresh rate (120Hz where available).
  // No-op / throws on platforms without the API — safe to ignore.
  try {
    await FlutterDisplayMode.setHighRefreshRate();
  } catch (_) {}
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    debugPrint('[main] Firebase init skipped: $e');
  }
  // Crash reporting: uncaught Flutter + async errors go to Crashlytics in
  // release builds. Debug runs keep reporting off so dev noise stays local.
  try {
    final crash = FirebaseCrashlytics.instance;
    await crash.setCrashlyticsCollectionEnabled(!kDebugMode);
    FlutterError.onError = crash.recordFlutterFatalError;
    PlatformDispatcher.instance.onError = (error, stack) {
      crash.recordError(error, stack, fatal: true);
      return true;
    };
  } catch (e) {
    debugPrint('[main] Crashlytics not available: $e');
  }
  // Plus Jakarta Sans ships in assets/google_fonts/, so google_fonts loads it
  // from the bundle: no network on first launch, no fallback-font flash, works
  // offline. Runtime fetching is off so a missing weight fails loudly in dev
  // instead of silently downloading.
  GoogleFonts.config.allowRuntimeFetching = false;
  LicenseRegistry.addLicense(() async* {
    final license = await rootBundle.loadString('assets/google_fonts/OFL.txt');
    yield LicenseEntryWithLineBreaks(['google_fonts'], license);
  });
  // Restore the amount-privacy toggle and display currency before the first
  // frame (no flash).
  try {
    final prefs = await SharedPreferences.getInstance();
    kAmountsHidden = prefs.getBool('amounts_hidden') ?? false;
    kInitialThemeMode = ThemeModeNotifier.parseThemeMode(
        prefs.getString('theme_mode') ?? 'dark');
    final code = prefs.getString('currency_code');
    if (code != null) kCurrency = Currencies.byCode(code);
  } catch (_) {}
  runApp(const ProviderScope(child: AerisExpenseApp()));
}
